/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guelamoviestore;

import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author 25078
 */
public class LoginFr extends javax.swing.JFrame {
    private String db_url="jdbc:mysql://localhost:3306/explore_movie_site_db";
    private String db_username="root";
    private String db_passwd=":@12ERgu#Oli";

    /**
     * Creates new form LoginFr
     */
    public LoginFr() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        txtPassword = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        userTypeCombo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));
        jPanel1.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Myanmar Text", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Sign In");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 94, 36));

        txtemail.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 180, 200, -1));

        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Don't have an account?");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 468, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 249, -1, -1));

        btnRegister.setForeground(new java.awt.Color(255, 0, 51));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 464, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("email");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 183, 60, -1));

        btnLogin.setForeground(new java.awt.Color(255, 0, 51));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 394, -1, -1));

        txtPassword.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 246, 200, -1));

        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("UserType");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 312, -1, -1));

        userTypeCombo.setForeground(new java.awt.Color(255, 0, 51));
        userTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "User" }));
        jPanel1.add(userTypeCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 309, 200, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\25078\\Desktop\\AUCA\\SMSTR6\\JAVA\\ProjectPic\\225f1820d95128837c6004a9654a7911.jpg")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 530, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        dispose();
        SignUpF signup = new SignUpF();
        signup.setVisible(true);
        
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        if(txtemail.getText().trim().isEmpty() || txtPassword.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "All fields should be filled");   
        }
        else{
            try{
                //String act
                Connection con = DriverManager.getConnection(db_url,db_username,db_passwd);
                PreparedStatement statement = con.prepareStatement("select email,password, roles from userstore where email = ? and password = ? and roles = ?");
                statement.setString(1, txtemail.getText());
                statement.setString(2, txtPassword.getText());
                statement.setString(3, String.valueOf(userTypeCombo.getSelectedItem()));
                ResultSet rs = statement.executeQuery();
                if(rs.next()){
                     if(userTypeCombo.getSelectedIndex() ==0){
                     JOptionPane.showMessageDialog(this, "Logged in successfully");
                     OperationsMovie op = new OperationsMovie();
                     dispose();
                     op.setVisible(true);
                     }
                     
                     else{
                             MovieSearch search = new MovieSearch();
                             dispose();
                             search.setVisible(true);
                     }
                }else{
                    JOptionPane.showMessageDialog(this, "email and password do not match");
                }
                 /*else{
                     JOptionPane.showMessageDialog(this, "check your queries", "error",JOptionPane.ERROR_MESSAGE);
                 }*/
        }catch(Exception ex){
            ex.printStackTrace();
        }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel *
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtemail;
    private javax.swing.JComboBox<String> userTypeCombo;
    // End of variables declaration//GEN-END:variables
}
