/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guelamoviestore;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author 25078
 */
public class MovieDisplay extends javax.swing.JFrame {

    DefaultTableModel tableModel = new DefaultTableModel();
    private String db_url="jdbc:mysql://localhost:3306/explore_movie_site_db";
    private String db_username="root";
    private String db_passwd=":@12ERgu#Oli";
    public MovieDisplay() {
        initComponents();
        addColumnTable();
        retrieveDataFromDbtoTable();
    }
    private void addColumnTable(){
        tableModel.addColumn("Serial_Number");
        tableModel.addColumn("Movie_Name");
        tableModel.addColumn("Director");
        tableModel.addColumn("Company_of_Production");
        tableModel.addColumn("Site_Name");
        
        MovieDisplayTable.setModel(tableModel);
        
    }
    
    private void retrieveDataFromDbtoTable(){
        try{
            Connection con = DriverManager.getConnection(db_url,db_username,db_passwd);
            PreparedStatement statement = con.prepareStatement("select *from moviedetails");
            ResultSet rs = statement.executeQuery();
            //con.close();
            while(rs.next()){
                tableModel.addRow(new Object[]{
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4),
                rs.getString(5)
                });
            }
            
            
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MovieDisplayTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, -120, 770, -1));

        MovieDisplayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        MovieDisplayTable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                MovieDisplayTableAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                MovieDisplayTableAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                MovieDisplayTableAncestorRemoved(evt);
            }
        });
        MovieDisplayTable.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                MovieDisplayTableMouseMoved(evt);
            }
        });
        jScrollPane1.setViewportView(MovieDisplayTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, 310));

        jLabel3.setBackground(new java.awt.Color(255, 51, 255));
        jLabel3.setText("Table Data");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 150, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\25078\\Desktop\\AUCA\\SMSTR6\\JAVA\\ProjectPic\\5b96f5e965e86cdee0c7bf0d1e7ec233.jpg")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MovieDisplayTableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_MovieDisplayTableAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_MovieDisplayTableAncestorAdded

    private void MovieDisplayTableAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_MovieDisplayTableAncestorRemoved
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(this, "Happy movie time !!!!!");
    }//GEN-LAST:event_MovieDisplayTableAncestorRemoved

    private void MovieDisplayTableAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_MovieDisplayTableAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_MovieDisplayTableAncestorMoved

    private void MovieDisplayTableMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovieDisplayTableMouseMoved
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Happy movie time !!!!!");
    }//GEN-LAST:event_MovieDisplayTableMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable MovieDisplayTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
